services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: laravel-app
        ports:
            - "80:80"
        networks:
            - laravel-network


    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: laravel-pma
        restart: always
        ports:
            - "8080:80"
        environment:
            MYSQL_ROOT_PASSWORD: root
            PMA_HOST: "{{ lookup('env','DB_HOST') }}"
            PMA_PORT: "{{ lookup('env','DB_PORT') }}"
            PMA_USER: "{{ lookup('env','DB_USERNAME') }}"
            PMA_PASSWORD: "{{ lookup('env','DB_PASSWORD') }}"
        networks:
            - laravel-network


networks:
    laravel-network:
        name: laravel-network
        driver: bridge
